<?php

return [
    'renderer' => 'mpdf',
    'disk' => env('DOCUMENTS_DISK', 'local'),
    'default_language' => env('DOCUMENTS_LANGUAGE', 'en'),
    'default_direction' => env('DOCUMENTS_DIRECTION', 'ltr'),
    'default_font' => env('DOCUMENTS_DEFAULT_FONT', 'dejavusans'),
    'queue' => [
        'enabled' => env('DOCUMENTS_QUEUE_ENABLED', false),
    ],
    'layout' => [
        'format' => 'A4',
        'orientation' => 'P',
        'margin_left' => 12,
        'margin_right' => 12,
        'margin_top' => 36,
        'margin_bottom' => 28,
        'margin_header' => 8,
        'margin_footer' => 8,
        'repeat_header' => true,
        'repeat_footer' => true,
    ],
    'templates' => [
        'layout' => 'core.documents.layouts.base',
        'header' => 'core.documents.layouts.header',
        'footer' => 'core.documents.layouts.footer',
    ],
    'types' => [
        'maintenance_check_in' => [
            'product_code' => 'maintenance',
            'module_code' => 'check_ins',
            'template' => 'products.automotive.documents.maintenance.check-in',
            'prefix' => 'CHKPDF',
            'title' => 'Vehicle Check-in Report',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'maintenance_work_order' => [
            'product_code' => 'maintenance',
            'module_code' => 'work_orders',
            'template' => 'products.automotive.documents.maintenance.work-order',
            'prefix' => 'WOPDF',
            'title' => 'Work Order',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'maintenance_estimate' => [
            'product_code' => 'maintenance',
            'module_code' => 'estimates',
            'template' => 'products.automotive.documents.maintenance.estimate',
            'prefix' => 'ESTPDF',
            'title' => 'Estimate',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'maintenance_delivery_report' => [
            'product_code' => 'maintenance',
            'module_code' => 'deliveries',
            'template' => 'products.automotive.documents.maintenance.delivery',
            'prefix' => 'DELPDF',
            'title' => 'Delivery Report',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'maintenance_warranty_certificate' => [
            'product_code' => 'maintenance',
            'module_code' => 'warranties',
            'template' => 'products.automotive.documents.maintenance.warranty',
            'prefix' => 'WARPDF',
            'title' => 'Warranty Certificate',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'accounting_tax_invoice' => [
            'product_code' => 'accounting',
            'module_code' => 'invoices',
            'template' => 'products.accounting.documents.tax-invoice',
            'prefix' => 'TAXINV',
            'title' => 'Tax Invoice',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'spareparts_delivery_note' => [
            'product_code' => 'spareparts',
            'module_code' => 'delivery_notes',
            'template' => 'products.spareparts.documents.delivery-note',
            'prefix' => 'SPDN',
            'title' => 'Spare Parts Delivery Note',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
    ],
];
