<?php

return [
    'renderer' => 'mpdf',
    'disk' => env('DOCUMENTS_DISK', 'local'),
    'default_language' => env('DOCUMENTS_LANGUAGE', 'en'),
    'default_direction' => env('DOCUMENTS_DIRECTION', 'ltr'),
    'default_font' => env('DOCUMENTS_DEFAULT_FONT', 'dejavusans'),
    'queue' => [
        'enabled' => env('DOCUMENTS_QUEUE_ENABLED', false),
    ],
    'layout' => [
        'format' => 'A4',
        'orientation' => 'P',
        'margin_left' => 12,
        'margin_right' => 12,
        'margin_top' => 36,
        'margin_bottom' => 28,
        'margin_header' => 8,
        'margin_footer' => 8,
        'repeat_header' => true,
        'repeat_footer' => true,
    ],
    'templates' => [
        'layout' => 'core.documents.layouts.base',
        'header' => 'core.documents.layouts.header',
        'footer' => 'core.documents.layouts.footer',
    ],
    'types' => [
        'maintenance_check_in' => [
            'product_key' => 'automotive',
            'product_code' => 'maintenance',
            'module_code' => 'check_ins',
            'document_key' => 'check_in',
            'template' => 'products.automotive.documents.maintenance.check-in',
            'prefix' => 'CHKPDF',
            'padding' => 4,
            'title' => 'Vehicle Check-in Report',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'maintenance_work_order' => [
            'product_key' => 'automotive',
            'product_code' => 'maintenance',
            'module_code' => 'work_orders',
            'document_key' => 'work_order',
            'template' => 'products.automotive.documents.maintenance.work-order',
            'prefix' => 'WOPDF',
            'padding' => 4,
            'title' => 'Work Order',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'maintenance_estimate' => [
            'product_key' => 'automotive',
            'product_code' => 'maintenance',
            'module_code' => 'estimates',
            'document_key' => 'estimate',
            'template' => 'products.automotive.documents.maintenance.estimate',
            'prefix' => 'ESTPDF',
            'padding' => 4,
            'title' => 'Estimate',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'maintenance_approval_certificate' => [
            'product_key' => 'automotive',
            'product_code' => 'maintenance',
            'module_code' => 'approvals',
            'document_key' => 'approval',
            'template' => 'products.automotive.documents.maintenance.approval-certificate',
            'prefix' => 'APPRPDF',
            'padding' => 4,
            'title' => 'Customer Approval Certificate',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'maintenance_invoice' => [
            'product_key' => 'automotive',
            'product_code' => 'maintenance',
            'module_code' => 'invoices',
            'document_key' => 'invoice',
            'template' => 'products.automotive.documents.maintenance.invoice',
            'prefix' => 'INVPDF',
            'padding' => 4,
            'title' => 'Maintenance Invoice',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'maintenance_receipt' => [
            'product_key' => 'automotive',
            'product_code' => 'maintenance',
            'module_code' => 'receipts',
            'document_key' => 'receipt',
            'template' => 'products.automotive.documents.maintenance.receipt',
            'prefix' => 'RECPDF',
            'padding' => 4,
            'title' => 'Maintenance Receipt',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'maintenance_delivery_report' => [
            'product_key' => 'automotive',
            'product_code' => 'maintenance',
            'module_code' => 'deliveries',
            'document_key' => 'delivery_report',
            'template' => 'products.automotive.documents.maintenance.delivery',
            'prefix' => 'DELPDF',
            'padding' => 4,
            'title' => 'Delivery Report',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'maintenance_warranty_certificate' => [
            'product_key' => 'automotive',
            'product_code' => 'maintenance',
            'module_code' => 'warranties',
            'document_key' => 'warranty_certificate',
            'template' => 'products.automotive.documents.maintenance.warranty',
            'prefix' => 'WARPDF',
            'padding' => 4,
            'title' => 'Warranty Certificate',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'automotive_job_card' => [
            'product_key' => 'automotive',
            'product_code' => 'maintenance',
            'module_code' => 'jobs',
            'document_key' => 'job_card',
            'template' => 'documents.products.automotive.job_card',
            'prefix' => 'JOB',
            'padding' => 4,
            'title' => 'Job Card',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'automotive_quotation' => [
            'product_key' => 'automotive',
            'product_code' => 'maintenance',
            'module_code' => 'quotations',
            'document_key' => 'quotation',
            'template' => 'documents.products.automotive.quotation',
            'prefix' => 'QUO',
            'padding' => 4,
            'title' => 'Quotation',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'accounting_tax_invoice' => [
            'product_key' => 'accounting',
            'product_code' => 'accounting',
            'module_code' => 'invoices',
            'document_key' => 'tax_invoice',
            'template' => 'documents.products.accounting.tax_invoice',
            'prefix' => 'TAXINV',
            'padding' => 4,
            'title' => 'Tax Invoice',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'accounting_payment_voucher' => [
            'product_key' => 'accounting',
            'product_code' => 'accounting',
            'module_code' => 'payments',
            'document_key' => 'payment_voucher',
            'template' => 'documents.products.accounting.payment_voucher',
            'prefix' => 'PV',
            'padding' => 4,
            'title' => 'Payment Voucher',
            'snapshot_required' => true,
            'qr_enabled' => false,
        ],
        'accounting_journal_voucher' => [
            'product_key' => 'accounting',
            'product_code' => 'accounting',
            'module_code' => 'journals',
            'document_key' => 'journal_voucher',
            'template' => 'documents.products.accounting.journal_voucher',
            'prefix' => 'JV',
            'padding' => 4,
            'title' => 'Journal Voucher',
            'snapshot_required' => true,
            'qr_enabled' => false,
        ],
        'accounting_statement_of_account' => [
            'product_key' => 'accounting',
            'product_code' => 'accounting',
            'module_code' => 'statements',
            'document_key' => 'statement_of_account',
            'template' => 'documents.products.accounting.statement_of_account',
            'prefix' => 'SOA',
            'padding' => 4,
            'title' => 'Statement of Account',
            'snapshot_required' => true,
            'qr_enabled' => false,
        ],
        'inventory_delivery_note' => [
            'product_key' => 'inventory',
            'product_code' => 'inventory',
            'module_code' => 'delivery_notes',
            'document_key' => 'delivery_note',
            'template' => 'documents.products.inventory.delivery_note',
            'prefix' => 'DN',
            'padding' => 4,
            'title' => 'Delivery Note',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'inventory_stock_transfer' => [
            'product_key' => 'inventory',
            'product_code' => 'inventory',
            'module_code' => 'transfers',
            'document_key' => 'stock_transfer',
            'template' => 'documents.products.inventory.stock_transfer',
            'prefix' => 'ST',
            'padding' => 4,
            'title' => 'Stock Transfer',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
        'inventory_purchase_order' => [
            'product_key' => 'inventory',
            'product_code' => 'inventory',
            'module_code' => 'purchase_orders',
            'document_key' => 'purchase_order',
            'template' => 'documents.products.inventory.purchase_order',
            'prefix' => 'PO',
            'padding' => 4,
            'title' => 'Purchase Order',
            'snapshot_required' => true,
            'qr_enabled' => true,
        ],
    ],
];
